# -*- coding: utf-8 -*-
"""Aku karakter pororo yang mana ya?

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDWlTbH_-ZnPriHaezBHFpb-sbCApoLq
"""

print("Aku karakter Pororo yang mana ya? Yuk, cek! ")
print("\nIni hari pertama kamu sekolah dan kamu ingin memperoleh banyak teman dengan membagikan roti,\nKamu punya 2 pilihan:\n1. Buat sendiri\n2. Beli roti di toko kue\n")
w=int(input("Kamu pilih yang mana?(1/2)= "))
print("\nKamu bertemu teman baru, \nKamu punya 2 pilihan: \n1. Sapa dia terlebih dahulu \n2.Tunggu ia menyapa mu")
y=int(input("Kamu pilih yang mana?(1/2)="))
print("\nTernyata, teman kamu sedang sedih, \nkamu harus melakukan sesuatu: \n1.Memberikan solusi untuk masalahnya \n2.Memeluk dia")
z=int(input("Apa yang kamu pilih?(1/2)="))

if w==1 and y==1 and z==1:
  print("\nSelamat, kamu adalah Petty yang hangat dan bijaksana ")
elif w==1 and y==1 and z==2:
  print ( "\nSelamat, kamu adalah Petty yang hangat dan berani")
elif w==1 and y==2 and z==1:
  print("\nSelamat, kamu adalah Eddy yang pemalu dan kreatif")
elif w==1 and y==2 and z==2:
  print("\nSelamat, kamu adalah Loopy  yang pemalu dan kreatif")
elif w==2 and y==1 and z==1:
  print("\nSelamat, kamu adalah Pororo yang ceria dan bijaksana")
elif w==2 and y==1 and z==2:
  print(" \nSelamat, kamu adalah Crong yang hangat namun berani")
elif w==2 and y==2 and z==1:
  print("\nSelamat, kamu adalah eddy yang praktis dan bijaksana")
elif w==2 and y==2 and z==2:
  print("\nSelamat, kamu adalah Crong versi pemalu ")
else :
  print("\n1kamu adalah diri mu sendiri yang unik!")